### ISSUE TITLE
Failed to install on Python 3.11

### ISSUE THREAD

**Issue by silane** [jorgeajimenezl/aiodav#9]
Failed to install on Python 3.11. It is likely that the dependency package `cchardet` is not working on Python 3.11.

Maybe replace `cchardet` package to `faust-cchardet`? since `cchardet` seems no longer maintained.

https://github.com/PyYoshi/cChardet/issues/81

https://github.com/faust-streaming/cChardet

```
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/cchardet
      copying src/cchardet/__init__.py -> build/lib.linux-aarch64-cpython-311/cchardet
      copying src/cchardet/version.py -> build/lib.linux-aarch64-cpython-311/cchardet
      running build_ext
      building 'cchardet._cchardet' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/src
      creating build/temp.linux-aarch64-cpython-311/src/cchardet
      creating build/temp.linux-aarch64-cpython-311/src/ext
      creating build/temp.linux-aarch64-cpython-311/src/ext/uchardet
      creating build/temp.linux-aarch64-cpython-311/src/ext/uchardet/src
      creating build/temp.linux-aarch64-cpython-311/src/ext/uchardet/src/LangModels
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/ext/uchardet/src -I/usr/local/include/python3.11 -c src/cchardet/_cchardet.cpp -o build/temp.linux-aarch64-cpython-311/src/cchardet/_cchardet.o
      src/cchardet/_cchardet.cpp:196:12: fatal error: longintrepr.h: No such file or directory
        196 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cchardet
  error: subprocess-exited-with-error
  
  × Running setup.py install for cchardet did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running install
      /usr/local/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/cchardet
      copying src/cchardet/__init__.py -> build/lib.linux-aarch64-cpython-311/cchardet
      copying src/cchardet/version.py -> build/lib.linux-aarch64-cpython-311/cchardet
      running build_ext
      building 'cchardet._cchardet' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/src
      creating build/temp.linux-aarch64-cpython-311/src/cchardet
      creating build/temp.linux-aarch64-cpython-311/src/ext
      creating build/temp.linux-aarch64-cpython-311/src/ext/uchardet
      creating build/temp.linux-aarch64-cpython-311/src/ext/uchardet/src
      creating build/temp.linux-aarch64-cpython-311/src/ext/uchardet/src/LangModels
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/ext/uchardet/src -I/usr/local/include/python3.11 -c src/cchardet/_cchardet.cpp -o build/temp.linux-aarch64-cpython-311/src/cchardet/_cchardet.o
      src/cchardet/_cchardet.cpp:196:12: fatal error: longintrepr.h: No such file or directory
        196 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cchardet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by jorgeajimenezl** [comment]
Fixed in https://github.com/jorgeajimenezl/aiodav/commit/3f94e95ea76452c2de93828ac812b6b8af8230fd
